version: '3'



# networks to be used by the services
networks:
  zfs_frnt_end:
  zfs_back_end:

volumes:
  zfs_mysql_vol:

services:
  zfs_host:
    container_name: zfs_host
    build:
      context: .
      dockerfile: zfs.Dockerfile
    image: zfs_img
    ports:
      - '8081:2584'
    networks:
      - zfs_back_end
    depends_on:
      - zfs_db

  zfs_db:
    image: mysql:8.0.30
    container_name: zfs_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: cisco12345
      MYSQL_DATABASE: fox_sheets
      MYSQL_USER: foxy
      MYSQL_PASSWORD: cisco12345
    networks:
      - zfs_back_end
    ports:
      - 3306:3306 # anything coming to localhost:3306, send it to [zfs_back_end-network]:3306
    volumes:
      - zfs_mysql_vol:/var/lib/mysql


  zfs_db_mgr:
    image: adminer:4.8.1
    container_name: zfs_db_adminer
    ports:
      - 8181:8080
    depends_on:
      - zfs_db
    networks:
      - zfs_back_end
