name: build image of core app

on: 
  push:
    branches:
      - "api_gateway"

jobs:
  build_app_docker_image:
    
    runs-on: ubuntu-20.04

    steps:
      - name: check-out code
        uses: actions/checkout@v3

      - name: identify the working directory
        run: ls -a

      # - name: build image using docker build command
      #   run: |


